CREATE TABLE EVENTO (ID_EVENTO INT PRIMARY KEY auto_increment, NOME_EVENTO VARCHAR(255), DATA_EVENTO DATE);
CREATE TABLE INGRESSO (ID_INGRESSO INT PRIMARY KEY auto_increment, TIPO_INGRESSO VARCHAR(255), VALOR_INGRESSO FLOAT);
INSERT INTO INGRESSO(TIPO_INGRESSO, VALOR_INGRESSO) VALUES ('VIP', 1000);
INSERT INTO INGRESSO(TIPO_INGRESSO, VALOR_INGRESSO) VALUES ('BACKSTAGE', 800);
INSERT INTO INGRESSO(TIPO_INGRESSO, VALOR_INGRESSO) VALUES ('PLATEIA VIP', 500);
INSERT INTO INGRESSO(TIPO_INGRESSO, VALOR_INGRESSO) VALUES ('PLATEIA', 300);