--Exclusão de tabelas
DROP TABLE IF EXISTS EVENTO;
DROP TABLE IF EXISTS INGRESSO;
DROP TABLE IF EXISTS INGRESSO_EVENTO;

--Criação de tabelas
CREATE TABLE EVENTO (
	ID_EVENTO INT auto_increment,
	NOME_EVENTO VARCHAR(255),
	DATA_EVENTO DATE,
	PRIMARY KEY (ID_EVENTO));
CREATE TABLE INGRESSO (
	ID_INGRESSO INT auto_increment,
	TIPO_INGRESSO VARCHAR(255),
	VALOR_INGRESSO FLOAT,
	PRIMARY KEY (ID_INGRESSO));
CREATE TABLE INGRESSO_EVENTO (
	ID_INGRESSO_EVENTO INT auto_increment,
	ID_EVENTO INT,
	ID_INGRESSO INT,
	INICIO_VENDA DATE,
	FINAL_VENDA DATE,
	PRIMARY KEY (ID_INGRESSO_EVENTO),
	FOREIGN KEY (ID_EVENTO) REFERENCES EVENTO(ID_EVENTO),
	FOREIGN KEY (ID_INGRESSO) REFERENCES INGRESSO(ID_INGRESSO));

--Inserção de dados
INSERT INTO EVENTO(NOME_EVENTO, DATA_EVENTO)
	VALUES ('Bon Jovi', '2017-10-19');
INSERT INTO EVENTO(NOME_EVENTO, DATA_EVENTO)
	VALUES ('The Who', '2017-10-26');
INSERT INTO EVENTO(NOME_EVENTO, DATA_EVENTO)
	VALUES ('Paul McCartney', '2017-10-13');
INSERT INTO EVENTO(NOME_EVENTO, DATA_EVENTO)
	VALUES ('John Mayer', '2017-10-24');

INSERT INTO INGRESSO(TIPO_INGRESSO, VALOR_INGRESSO)
	VALUES ('VIP', 1000);
INSERT INTO INGRESSO(TIPO_INGRESSO, VALOR_INGRESSO)
	VALUES ('BACKSTAGE', 800);
INSERT INTO INGRESSO(TIPO_INGRESSO, VALOR_INGRESSO)
	VALUES ('PLATEIA VIP', 500);
INSERT INTO INGRESSO(TIPO_INGRESSO, VALOR_INGRESSO)
	VALUES ('PLATEIA', 300);

--INSERT INTO INGRESSO_EVENTO(ID_EVENTO, ID_INGRESSO, INICIO_VENDA, FINAL_VENDA)
--	VALUES (1, 2, '2017-06-01', '2017-08-31');
--INSERT INTO INGRESSO_EVENTO(ID_EVENTO, ID_INGRESSO, INICIO_VENDA, FINAL_VENDA)
--	VALUES (1, 20, '2017-06-01', '2017-08-31');